package io.aethibo.features.articles.domain.mapper

import io.aethibo.features.articles.data.model.ArticleEntity
import io.aethibo.features.articles.domain.model.Article
import io.aethibo.features.articles.presentation.model.*
import io.aethibo.features.users.domain.model.User
import org.jetbrains.exposed.v1.core.ResultRow
import java.time.format.DateTimeFormatter

fun ResultRow.toArticleDomain(author: User): Article = Article(
    slug = this[ArticleEntity.slug],
    title = this[ArticleEntity.title],
    description = this[ArticleEntity.description],
    body = this[ArticleEntity.body],
    createdAt = this[ArticleEntity.createdAt],
    updatedAt = this[ArticleEntity.updatedAt],
    author = author
)

fun CreateArticleRequest.toDomain(): Article = Article(
    slug = "", // will be generated by service
    title = this.title,
    description = this.description,
    body = this.body,
    tagList = this.tagList,
    createdAt = null, // DB will fill automatically
    updatedAt = null, // DB will fill automatically
)

fun UpdateArticleRequest.toDomain(): Article = Article(
    slug = "", // set by service
    title = this.title ?: "",
    description = this.description ?: "",
    body = this.body ?: "",
    tagList = this.tagList ?: listOf(),
    createdAt = null, // preserve DB value
    updatedAt = null, // will be updated automatically
)

fun Article.toArticleResponseDto(): ArticleResponseDto {
    val formatter = DateTimeFormatter.ISO_DATE_TIME

    return ArticleResponseDto(
        slug = slug!!,
        title = title!!,
        description = description!!,
        body = body,
        tagList = tagList,
        createdAt = createdAt?.format(formatter) ?: "",
        updatedAt = updatedAt?.format(formatter) ?: "",
        favorited = favorited,
        favoritesCount = favoritesCount,
        author = author!!.toUserResponseDto()
    )
}

fun List<Article>.toArticlesResponseDto(): ArticlesResponseDto =
    ArticlesResponseDto(
        articles = this.map { it.toArticleResponseDto() },
        articlesCount = this.size
    )

fun User.toUserResponseDto(): UserResponseDto =
    UserResponseDto(
        username = this.username!!,
        email = this.email,
        bio = this.bio,
        image = this.image
    )
